/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");
const path = require("path");

const app = express();

app.use(bodyParser.json());

const TODOS_FILE = path.join(__dirname, "todos.json");

const todos = [];
let id = 1;

function loadTodos() {
  try {
    const data = fs.readFileSync(TODOS_FILE, "utf-8");
    const savedTodos = JSON.parse(data);
    todos.push(...savedTodos);
  } catch (err) {
    // file doesn't exist yet or is invalid/empty, start with no todos
  }

  const maxId = todos.reduce((max, t) => Math.max(max, t.id), 0);
  id = maxId + 1;
}

function saveTodos() {
  fs.writeFileSync(TODOS_FILE, JSON.stringify(todos, null, 2));
}

loadTodos();

app.get("/", (req, res) => {
  res.send("hi world");
});

app.get("/todos", getAllTodos);
app.get("/todos/:id", getTodo);

app.post("/todos", postTodo);

app.put("/todos/:id", updateTodo);

app.delete("/todos/:id", deleteTodo);

function getAllTodos(req, res) {
  res.status(200).json(todos);
}

function getTodo(req, res) {
  const id = parseInt(req.params.id);
  const todo = todos.find((t) => t.id === id);

  if (!todo) return res.sendStatus(404);

  res.status(200).json(todo);
}

function postTodo(req, res) {
  const title = req.body.title;
  const description = req.body.description;
  let postId = id;
  id++;
  const newTodo = { id: postId, title, description };
  todos.push(newTodo);
  saveTodos();

  res.status(201).json(newTodo);
}

function updateTodo(req, res) {
  const id = parseInt(req.params.id);
  const newTitle = req.body.title;
  const newDescription = req.body.description;

  const index = todos.findIndex((t) => t.id === id);
  if (index === -1) return res.sendStatus(404);

  todos[index].title = newTitle || todos[index].title;
  todos[index].description = newDescription || todos[index].description;
  saveTodos();

  res.sendStatus(200);
}

function deleteTodo(req, res) {
  const id = parseInt(req.params.id);
  const index = todos.findIndex((t) => t.id === id);

  if (index === -1) return res.sendStatus(404);

  todos.splice(index, 1);
  saveTodos();

  res.sendStatus(200);
}

app.use((req, res) => {
  res.sendStatus(404);
});

module.exports = app;
